#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Load my alias file
if [ -f ~/.bash_aliases ]; then
        source ~/.bash_aliases
else
        print "404:alias not found."
fi

# Reload zsh shell
alias rl="source ~/.zshrc"
